### ISSUE TITLE
rsync permission denied in Docker version

### ISSUE THREAD

**Issue by chenchen2015** [trailofbits/algo#1242] opened 2018-12-08 18:52 UTC
**Describe the bug**

Running the docker version ended with `rsync` permission error and did not sync any config files.

**To Reproduce**

1. Start fresh Ubuntu 18.04 x64 instance on EC2 (t3.small)
2. Installed docker - `sudo snap install docker`
3. `sudo docker run --cap-drop ALL -it -v /home/ubuntu/algovpn:/data trailofbits/algo:latest`, where `/home/ubuntu/algovpn` is a folder that includes the `config.cfg` file.

Got error right after the success message:
```
TASK [debug] *************************************************************************************************************************************
ok: [***] => {
    "msg": [
        [
            "\"#                          Congratulations!                            #\"",
            "\"#                     Your Algo server is running.                     #\"",
            "\"#    Config files and certificates are in the ./configs/ directory.    #\"",
            "\"#              Go to https://whoer.net/ after connecting               #\"",
            "\"#        and ensure that all your traffic passes through the VPN.      #\"",
            "\"#                     Local DNS resolver 172.16.0.1                    #\"",
            ""
        ],
        "    \"#        The p12 and SSH keys password for new users is ***       #\"\n",
        "    ",
        "    \"#      Shell access: ssh -i configs/algo.pem ***        #\"\n"
    ]
}

PLAY RECAP ***************************************************************************************************************************************
***                        : ok=135  changed=88   unreachable=0    failed=0
localhost                  : ok=35   changed=8    unreachable=0    failed=0

rsync: recv_generator: mkdir "/data/configs" failed: Permission denied (13)
*** Skipping any contents from this failed directory ***
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1189) [sender=3.1.3]
```

Raw IP addresses were removed and replaced by `*`.

No configuration file was copied and hence I have no access to the deployed VPN.

**Expected behavior**

According to the [Docker instructions](https://github.com/trailofbits/algo/blob/master/docs/deploy-from-docker.md)

```
When it exits, you'll be left with a fully populated configs directory, 
containing all appropriate configuration data for your clients, and for 
future server management
```

**Additional context**

```
--> Please include the following block of text when reporting issues:

Algo running on: Alpine Linux v3.8 (Virtualized: docker)
ZIP file created: 2018-12-03 17:34:56.000000000
Python 2.7.15
Runtime variables:
    algo_provider "local"
    algo_ondemand_cellular "False"
    algo_ondemand_wifi "False"
    algo_ondemand_wifi_exclude "_null"
    algo_local_dns "False"
    algo_ssh_tunneling "False"
    algo_windows "False"
    wireguard_enabled "True"
    dns_encryption "True"

```

**Comment by jackivanov** [comment] 2018-12-10 09:48
Why do you run docker command with sudo?

**Comment by chenchen2015** [comment] 2018-12-10 23:47
Running `docker` with or without `sudo` does not matter. The result is the same.

I just tried again with the exact same procedure but with the `docker` user group configured as well (per instruction on [https://docs.docker.com/install/linux/linux-postinstall/](https://docs.docker.com/install/linux/linux-postinstall/)). I am getting the exact same error.

**Comment by jackivanov** [comment] 2018-12-11 13:18
Hmm, OK. 
I suppose, it's related to apparmor.  https://docs.docker.com/engine/security/apparmor/ Could you check that please?

**Comment by jackivanov** [comment] 2018-12-18 10:42
Closing for now

**Closed by jackivanov** 2018-12-18 10:42 UTC

**Comment by dlipovetsky** [comment] 2019-01-29 06:46
I am able to reproduce this issue on Linux. The cause is that root inside the algo container is unable to write to the bind-mounted configuration directory, most likely because it is owned by a different user and is not world-writable. (The user mismatch is a well-known problem with bind-mounts into docker containers.)

Like @chenchen2015, I ran into a write permission issue bind-mounting my configuration directory on the host  to `/data` in the container. I worked around this by changing the owner of the directory on the host to root (uid 0) by running `sudo chown -R 0:0 /path/to/dir/on/host`.

I also ran into a read permission issue bind-mounting my `.ssh` directory to `/root/.ssh` in the algo container in order to give the algo install tool ssh credentials. I worked around this by first copying my `~/.ssh` directory and then changing the owner of the copy to root (uid 0) by running `sudo chown -R 0:0 /path/to/copy-of-.ssh/`.

Note that the above workaround requires root privileges (to run `chown 0:0`). But any user able to interact with the docker daemon typically has root privileges.

I imagine anyone running algo in a docker container will have a similar experience, so I'd like to file a PR against the "deploy with docker" documentation. But I'm leaving this note here in the meantime.

**Comment by elreydetoda** [comment] 2019-10-16 02:59
So, looking at @dlipovetsky's solution I figured it was a permissions issue that normally docker has the ability to override, because I haven't had problems with bind mounts in the past when running without dropping capabilities, so I narrowed the permissions down to the following docker command that can run and save everything properly (without changing the UID/GID of the folders and files):

```
docker container run -it -v "$(pwd)":/data --cap-drop=all --cap-add=DAC_OVERRIDE --cap-add=FOWNER --rm trailofbits/algo:latest
```

screenshot of the permissions after running algo as docker
![image](https://user-images.githubusercontent.com/10230166/66884477-510a9f80-ef9f-11e9-846b-42b662b49de2.png)

So, when run it has the ability to bypass the permissions check that requires the UID of the process to match the UID of the file and also bypass file read, write, and execute permissions checks. To learn more you can checkout this area in the docker docs: https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities

The other way to solve this problem is to implement a solution like the @linuxserver team has done: https://docs.linuxserver.io/general/understanding-puid-and-pgid. That seemed like a lot of work though for a pull request, so instead I can run the above command and everything saves as the owning user 

Would the project like me to submit a pull request for the docs to update the docker command to reflect the one I put above, or would they consider that not secure enough?
