### ISSUE TITLE
GCE: Could not locate credentials JSON file

### ISSUE THREAD

**Issue by 13mik13** [trailofbits/algo#1299] opened 2019-01-14 21:24 UTC
Could any one help with that?

fatal: [localhost]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'file'. Error was a <class 'ansible.errors.AnsibleError'>, original message: could not locate file in lookup: /Users/mik/algo-master/My\\ First\\ Project-fa1a323a8348.json "}

Thanks!

TASK [Gathering Facts] *********************************************************
ok: [localhost]
[pause]
What provider would you like to use?
    1. DigitalOcean
    2. Amazon Lightsail
    3. Amazon EC2
    4. Vultr
    5. Microsoft Azure
    6. Google Compute Engine
    7. Scaleway
    8. OpenStack (DreamCompute optimised)
    9. Install to existing Ubuntu 18.04 server (Advanced)
  
Enter the number of your desired provider
:
6

TASK [pause] *******************************************************************
ok: [localhost]

TASK [Set facts based on the input] ********************************************
ok: [localhost]
[pause]
Name the vpn server
[algo]
:

TASK [pause] *******************************************************************
ok: [localhost]
[pause]
Do you want macOS/iOS clients to enable "VPN On Demand" when connected to cellular networks?
[y/N]
:
n

TASK [pause] *******************************************************************
ok: [localhost]
[pause]
Do you want macOS/iOS clients to enable "VPN On Demand" when connected to Wi-Fi?
[y/N]
:
n

TASK [pause] *******************************************************************
ok: [localhost]
[pause]
Do you want to install a DNS resolver on this VPN server, to block ads while surfing?
[y/N]
:
n

TASK [pause] *******************************************************************
ok: [localhost]
[pause]
Do you want each user to have their own account for SSH tunneling?
[y/N]
:
n

TASK [pause] *******************************************************************
ok: [localhost]
[pause]
Do you want the VPN to support Windows 10 or Linux Desktop clients? (enables compatible ciphers and key exchange, less secure)
[y/N]
:
y

TASK [pause] *******************************************************************
ok: [localhost]
[pause]
Do you want to retain the CA key? (required to add users in the future, but less secure)
[y/N]
:
n

TASK [pause] *******************************************************************
ok: [localhost]

TASK [Set facts based on the input] ********************************************
ok: [localhost]

PLAY [Provision the server] ****************************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

--> Please include the following block of text when reporting issues:

Algo running on: Mac OS X 10.14.2
ZIP file created: Jan  7 23:57:40 2019
Python 2.7.10
Runtime variables:
    algo_provider "gce"
    algo_ondemand_cellular "False"
    algo_ondemand_wifi "False"
    algo_ondemand_wifi_exclude "_null"
    algo_local_dns "False"
    algo_ssh_tunneling "False"
    algo_windows "True"
    wireguard_enabled "True"
    dns_encryption "True"

TASK [Display the invocation environment] **************************************
changed: [localhost -> localhost]

TASK [Install the requirements] ************************************************
ok: [localhost -> localhost]

TASK [Generate the SSH private key] ********************************************
ok: [localhost]

TASK [Generate the SSH public key] *********************************************
ok: [localhost]

TASK [cloud-gce : Install requirements] ****************************************
ok: [localhost]
[cloud-gce : pause]
Enter the local path to your credentials JSON file
(https://support.google.com/cloud/answer/6158849?hl=en&ref_topic=6262490#serviceaccounts)
:
/Users/mik/algo-master/My\ First\ Project-fa1a323a8348.json 

TASK [cloud-gce : pause] *******************************************************
ok: [localhost]

TASK [cloud-gce : set_fact] ****************************************************
ok: [localhost]
 [WARNING]: Unable to find '/Users/mik/algo-master/My\ First\ Project-
fa1a323a8348.json ' in expected paths (use -vvvvv to see paths)

TASK [cloud-gce : set_fact] ****************************************************
fatal: [localhost]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'file'. Error was a <class 'ansible.errors.AnsibleError'>, original message: could not locate file in lookup: /Users/mik/algo-master/My\\ First\\ Project-fa1a323a8348.json "}

TASK [cloud-gce : debug] *******************************************************
ok: [localhost] => {
    "fail_hint": [
        "Sorry, but something went wrong!", 
        "Please check the troubleshooting guide.", 
        "https://trailofbits.github.io/algo/troubleshooting.html"
    ]
}

TASK [cloud-gce : fail] ********************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed as requested from task"}

PLAY RECAP *********************************************************************
localhost                  : ok=20   changed=1    unreachable=0    failed=2

**Comment by 13mik13** [comment] 2019-01-15 08:53
I've tried. Several times under different simple names: algo.json, google.json. my.json
I've also tried to put json into different folders: algo-master, Downloads, other locations.
Same error

**Comment by jackivanov** [comment] 2019-01-26 06:11
I couldn't reproduce this. Try to run algo in verbose mode `-vvvv` and put the log here

**Comment by jackivanov** [comment] 2019-01-30 06:41
Unreproducible. Closing for now. File another issue when you have more info

**Closed by jackivanov** 2019-01-30 06:41 UTC

**Comment by stheoret** [comment] 2020-02-16 20:39
Hi !  Yep ! I had the same issue man... So you can solves this by going to :   https://cloud.google.com/docs/authentication/getting-started?hl=en   and go to your Google console to create a JSON access file for your compute engine. Press the blue button (( Go to the Create Service Account Key page )) and select " compute engine", then JSON file if not the default, create it and then the download should activate itself.... Once done, upload the file to your path with the ssh window ( upper right mechanical icon ) -- upload file, then put this in the ALGO SCRIPT for the path for the JSON FILE ....   should be :    /home/your specific folder name/API Project-whateverhere.json

Works perfectly for me !

Stephane

**Comment by jetadidas** [comment] 2023-01-15 17:21
> Hi ! Yep ! I had the same issue man... So you can solves this by going to : https://cloud.google.com/docs/authentication/getting-started?hl=en and go to your Google console to create a JSON access file for your compute engine. Press the blue button (( Go to the Create Service Account Key page )) and select " compute engine", then JSON file if not the default, create it and then the download should activate itself.... Once done, upload the file to your path with the ssh window ( upper right mechanical icon ) -- upload file, then put this in the ALGO SCRIPT for the path for the JSON FILE .... should be : /home/your specific folder name/API Project-whateverhere.json
> 
> Works perfectly for me !
> 
> Stephane

You rock Stephane!,
Thank you for your help in this! The hardest part was finding this comment.
