### ISSUE TITLE
Can connect to VPN but sites do not respond

### ISSUE THREAD

**Issue by joshwardell** [trailofbits/algo#310] opened 2017-03-30 00:42 UTC
### OS / Environment

MacOS 10.12.4
iOS 10.3

### Summary of the problem

Successfully deployed Algo to google cloud engine. Installed mobileconfig profile to both Mac and iPhone. Both connect to VPN immediately. They stay connected, but I can't get any sites to load. Browser just sits there waiting for a response.

I tried adding google DNS servers, what else should I be looking at or trying?

**Comment by senoird** [comment] 2017-03-30 00:55
Same issue here. Also using Google cloud engine.

**Comment by jhunken** [comment] 2017-03-30 03:57
Looks like duplicate of #210

**Closed** 2017-03-30 05:05 UTC
Labels: duplicate

**Comment by joshwardell** [comment] 2017-03-30 19:43
Not the same as #210, I can't get traffic to any site. Glad to see someoelse else is having the issue. Does anyone using google cloud have Algo working? Both of these are closed without being resolved :(
(I'm using Google because no other server is free!)

**Comment by dguido** [comment] 2017-03-30 20:39
AWS has a free tier

**Comment by chadmasso** [comment] 2017-03-30 21:43
I'm, also running into this issue using GCE

**Comment by dguido** [comment] 2017-03-30 21:49
MTU issues are more common on GCE than other providers. If you have troubleshooting instructions to contribute, please add them to #210. Thanks!

**Comment by kiratp** [comment] 2017-04-03 04:24
I seem to be in the same boat. Azure works, GCE does not. Ping works but I am seeing 100% failure for DNS requests from the client - dig, curl, safari and Chrome all fail to receive any responses.


`$ ping -D -s 1373 8.8.8.8
PING 8.8.8.8 (8.8.8.8): 1373 data bytes
ping: sendto: Message too long
ping: sendto: Message too long`

` ping -D -s 1372 8.8.8.8
PING 8.8.8.8 (8.8.8.8): 1372 data bytes
72 bytes from 8.8.8.8: icmp_seq=0 ttl=52 time=19.703 ms
wrong total length 92 instead of 1400`


Server MTU: 1460
Client tunnel MTU: 1400

Tried to drop the server side MTU with the following but it made no difference
`iptables -t mangle -A FORWARD -o eth0 -p tcp -m tcp --tcp-flags SYN,RST SYN -m tcpmss --mss 1361:1536 -j TCPMSS --set-mss 1360`
