### ISSUE TITLE
GCE deployment failed

### ISSUE THREAD

**Issue by happy201807** [trailofbits/algo#1184] opened 2018-10-31 10:31 UTC
> failed: [35.IP] (item=[u'python2.7', u'sudo']) => {"changed": false, "item": ["python2.7", "sudo"], "msg": "No package matching 'python2.7' is available"}

Ubuntu 18.04 LTS

The installation was successful before using the script, but it has always failed recently. How can I solve this error?

**Comment by jackivanov** [comment] 2018-11-09 13:34
Can't reproduce. Closing for now. Could you check that now from scratch and file another issue if it happens again, please? And use the issue form, please

**Closed by jackivanov** 2018-11-09 13:34 UTC
