### ISSUE TITLE
Failure using Ubuntu 20.04 under WSL

### ISSUE THREAD

**Issue by jianjianerluka** [trailofbits/algo#1812] opened 2020-05-25 12:16 UTC
after I cd algo and type ./algo, I could not match supplied host pattern,

the details are here
[WARNING]: Could not match supplied host pattern, ignoring: VPN-host

PLAY [localhost] *******************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************
fatal: [localhost]: UNREACHABLE! => {"changed": false, "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p \"` echo /home/erii/.ansible/tmp/ansible-tmp-1590408807.0114243-274381255770791 `\" && echo ansible-tmp-1590408807.0114243-274381255770791=\"` echo /home/erii/.ansible/tmp/ansible-tmp-1590408807.0114243-274381255770791 `\" ), exited with result 1, stdout output: ansible-tmp-1590408807.0114243-274381255770791=/home/erii/.ansible/tmp/ansible-tmp-1590408807.0114243-274381255770791\n", "unreachable": true}

PLAY RECAP *************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0
```

**Comment by jianjianerluka** [comment] 2020-05-25 12:17
the system is Windows 10, last version

**Comment by davidemyers** [comment] 2020-05-25 12:20
> [WARNING]: Could not match supplied host pattern, ignoring: VPN-host

That's a normal message.

This looks like a duplicate of #1811.

**Comment by davidemyers** [comment] 2020-05-25 12:33
Issue #1811 was closed by using Ubuntu 18.04 under WSL instead of 20.04 (which I guess is now the default).

Why don't you change the title of this issue to something like "Failure using Ubuntu 20.04 under WSL" and leave it open until someone figures out how to fix it?

**Comment by jianjianerluka** [comment] 2020-05-25 12:36
thank you for your suggestion. I changed the title and try to use Ubuntu 18.04 to deploy

**Comment by jackivanov** [comment] 2020-05-30 12:58
We need to address this issue in docs

**Comment by betellen** [comment] 2020-06-14 10:21
I found the root cause for the problem and a workaround here:
https://community.spiceworks.com/topic/2275812-ubuntu-wsl-ansible-permission-error-when-running-localhost-playbook

**Closed** 2020-09-05 06:34 UTC
Labels: documentation, needs_pr
