### ISSUE TITLE
Can't connect to VPN server deployed on local machine

### ISSUE THREAD

**Issue by gergely-sallai** [trailofbits/algo#721] opened 2017-11-12 19:54 UTC
### OS / Environment
Raspberry Pi Model B+ (512 MB) Raspbian

### Ansible version
ansible 2.2.0.0

### Summary of the problem
This is more of a question really: 
- Can I run Algo on the above setup?
- If yes, what am I doing wrong?

Installation completed successfully.
Ports 500 UDP and 4500 UDP are forwarded.
Everything seems to be working but can't connect through strongSwan Android.
It seems to be communicating but fails to establish connection.

### Logs from strongSwan Android
```
Nov 12 19:56:31 00[DMN] Starting IKE charon daemon (strongSwan 5.6.0, Android 6.0.1 - 23.5.A.1.291/2016-05-01, D5803 - Sony/D5803/Sony, Linux 3.4.0-perf-gc14c2d5, armv7l)
Nov 12 19:56:31 00[LIB] loaded plugins: androidbridge charon android-log openssl fips-prf random nonce pubkey chapoly curve25519 pkcs1 pkcs8 pem xcbc hmac socket-default revocation eap-identity eap-mschapv2 eap-md5 eap-gtc eap-tls x509
Nov 12 19:56:31 00[JOB] spawning 16 worker threads
Nov 12 19:56:31 07[CFG] loaded user certificate 'CN=gomi' and private key
Nov 12 19:56:31 07[CFG] loaded CA certificate 'CN=<VPN SERVER IP>'
Nov 12 19:56:31 07[IKE] initiating IKE_SA android[1] to <VPN SERVER IP>
Nov 12 19:56:31 07[ENC] generating IKE_SA_INIT request 0 [ SA KE No N(NATD_S_IP) N(NATD_D_IP) N(FRAG_SUP) N(HASH_ALG) N(REDIR_SUP) ]
Nov 12 19:56:31 07[NET] sending packet: from <CLIENT IP>[56112] to <VPN SERVER IP>[500] (746 bytes)
Nov 12 19:56:31 10[NET] received packet: from <VPN SERVER IP>[500] to <CLIENT IP>[56112] (289 bytes)
Nov 12 19:56:31 10[ENC] parsed IKE_SA_INIT response 0 [ SA KE No N(NATD_S_IP) N(NATD_D_IP) CERTREQ N(FRAG_SUP) N(HASH_ALG) N(MULT_AUTH) ]
Nov 12 19:56:31 10[IKE] local host is behind NAT, sending keep alives
Nov 12 19:56:31 10[IKE] remote host is behind NAT
Nov 12 19:56:32 10[IKE] received cert request for "CN=<VPN SERVER IP>"
<CERT REQUESTS TO OTHER CAs>
Nov 12 19:56:32 10[IKE] sending cert request for "CN=<VPN SERVER IP>"
Nov 12 19:56:32 10[IKE] authentication of 'CN=gomi' (myself) with ECDSA_WITH_SHA256_DER successful
Nov 12 19:56:32 10[IKE] sending end entity cert "CN=gomi"
Nov 12 19:56:32 10[IKE] establishing CHILD_SA android{1}
Nov 12 19:56:32 10[ENC] generating IKE_AUTH request 1 [ IDi CERT N(INIT_CONTACT) CERTREQ AUTH CPRQ(ADDR ADDR6 DNS DNS6) N(ESP_TFC_PAD_N) SA TSi TSr N(MOBIKE_SUP) N(NO_ADD_ADDR) N(MULT_AUTH) N(EAP_ONLY) N(MSG_ID_SYN_SUP) ]
Nov 12 19:56:32 10[ENC] splitting IKE message with length of 4174 bytes into 4 fragments
Nov 12 19:56:32 10[ENC] generating IKE_AUTH request 1 [ EF(1/4) ]
Nov 12 19:56:32 10[ENC] generating IKE_AUTH request 1 [ EF(2/4) ]
Nov 12 19:56:32 10[ENC] generating IKE_AUTH request 1 [ EF(3/4) ]
Nov 12 19:56:32 10[ENC] generating IKE_AUTH request 1 [ EF(4/4) ]
Nov 12 19:56:32 10[NET] sending packet: from <CLIENT IP>[60888] to <VPN SERVER IP>[4500] (1248 bytes)
Nov 12 19:56:32 10[NET] sending packet: from <CLIENT IP>[60888] to <VPN SERVER IP>[4500] (1248 bytes)
Nov 12 19:56:32 10[NET] sending packet: from <CLIENT IP>[60888] to <VPN SERVER IP>[4500] (1248 bytes)
Nov 12 19:56:32 10[NET] sending packet: from <CLIENT IP>[60888] to <VPN SERVER IP>[4500] (617 bytes)
Nov 12 19:56:34 12[IKE] retransmit 1 of request with message ID 1
Nov 12 19:56:34 12[NET] sending packet: from <CLIENT IP>[60888] to <VPN SERVER IP>[4500] (1248 bytes)
Nov 12 19:56:34 12[NET] sending packet: from <CLIENT IP>[60888] to <VPN SERVER IP>[4500] (1248 bytes)
Nov 12 19:56:34 12[NET] sending packet: from <CLIENT IP>[60888] to <VPN SERVER IP>[4500] (1248 bytes)
Nov 12 19:56:34 12[NET] sending packet: from <CLIENT IP>[60888] to <VPN SERVER IP>[4500] (617 bytes)
Nov 12 19:56:34 13[NET] received packet: from <VPN SERVER IP>[4500] to <CLIENT IP>[60888] (741 bytes)
Nov 12 19:56:34 13[ENC] parsed IKE_AUTH response 1 [ IDr CERT AUTH CPRP(ADDR ADDR6 DNS DNS) N(MOBIKE_SUP) N(NO_ADD_ADDR) N(NO_PROP) ]
Nov 12 19:56:34 13[IKE] received end entity cert "CN=<VPN SERVER IP>"
Nov 12 19:56:34 13[CFG]   using certificate "CN=<VPN SERVER IP>"
Nov 12 19:56:34 13[CFG]   using trusted ca certificate "CN=<VPN SERVER IP>"
Nov 12 19:56:34 13[CFG] checking certificate status of "CN=<VPN SERVER IP>"
Nov 12 19:56:34 13[CFG] certificate status is not available
Nov 12 19:56:34 13[CFG]   reached self-signed root ca with a path length of 0
Nov 12 19:56:34 13[IKE] authentication of '<VPN SERVER IP>' with ECDSA_WITH_SHA256_DER successful
Nov 12 19:56:34 14[MGR] ignoring request with ID 1, already processing
Nov 12 19:56:34 13[IKE] IKE_SA android[1] established between <CLIENT IP>[CN=gomi]...<VPN SERVER IP>[<VPN SERVER IP>]
Nov 12 19:56:34 13[IKE] scheduling rekeying in 35918s
Nov 12 19:56:34 13[IKE] maximum IKE_SA lifetime 36518s
Nov 12 19:56:34 13[IKE] installing DNS server 8.8.8.8
Nov 12 19:56:34 13[IKE] installing DNS server 8.8.4.4
Nov 12 19:56:34 13[IKE] installing new virtual IP 10.19.48.1
Nov 12 19:56:34 13[IKE] installing new virtual IP fd9d:bc11:4020::1
Nov 12 19:56:34 13[IKE] received NO_PROPOSAL_CHOSEN notify, no CHILD_SA built
Nov 12 19:56:34 13[IKE] closing IKE_SA due CHILD_SA setup failure
Nov 12 19:56:34 13[IKE] peer supports MOBIKE
Nov 12 19:56:34 15[IKE] deleting IKE_SA android[1] between <CLIENT IP>[CN=gomi]...<VPN SERVER IP>[<VPN SERVER IP>]
Nov 12 19:56:34 15[IKE] sending DELETE for IKE_SA android[1]
Nov 12 19:56:34 15[ENC] generating INFORMATIONAL request 2 [ D ]
Nov 12 19:56:34 15[NET] sending packet: from <CLIENT IP>[60888] to <VPN SERVER IP>[4500] (65 bytes)
Nov 12 19:56:34 16[NET] received packet: from <VPN SERVER IP>[4500] to <CLIENT IP>[60888] (57 bytes)
Nov 12 19:56:34 16[ENC] parsed INFORMATIONAL response 2 [ ]
Nov 12 19:56:34 16[IKE] IKE_SA deleted
```

**Comment by catcarbon** [comment] 2017-11-12 21:50
Duplicate of #611

**Comment by dguido** [comment] 2017-11-12 23:41
It looks like the pertinent bits are here:

```
Nov 12 19:56:34 13[IKE] received NO_PROPOSAL_CHOSEN notify, no CHILD_SA built
Nov 12 19:56:34 13[IKE] closing IKE_SA due CHILD_SA setup failure
```

I would recommend what catcarbon said, check out the docs extra closely and followup with either the Gitter or with the strongswan community for support. I don't think this is a bug in Algo right now.

**Closed by dguido** 2017-11-12 23:41 UTC
