### ISSUE TITLE
Add support for making server with Amazon Lightsail

### ISSUE THREAD

**Issue by computerality** [trailofbits/algo#136] opened 2016-11-30 17:46 UTC
Amazon launched a digital ocean equivalent today. amazonlightsail.com It would be nice to have support for using this in algo.

The API docs don't seem to be up just yet but will bet at 
http://docs.aws.amazon.com/lightsail/2016-11-28/api-reference/Welcome.html

**Comment by defunctio** [comment] 2016-12-07 16:14
Looks like documentation went live as of the 6th. I can confirm lightsail client exists in the latest botocore as well.
```
>>> from botocore import session
>>> session.get_session().create_client('lightsail', region_name='us-east-1')
<botocore.client.Lightsail object at 0x7f26128fba10>
```
I don't think there has been any efforts to implement this into ansible yet though.

**Comment by defunctio** [comment] 2016-12-09 16:25
docs: http://boto3.readthedocs.io/en/latest/reference/services/lightsail.html

**Comment by defunctio** [comment] 2016-12-31 15:41
@gunph1ld status?

**Comment by defunctio** [comment] 2017-01-10 20:48
This is in progress: https://github.com/ansible/ansible/pull/19846
We should likely see this in 2.3.

**Comment by feoh** [comment] 2017-03-29 20:37
It's been merged!
https://github.com/ansible/ansible/pull/19846

**Comment by lordmuffin** [comment] 2017-04-13 21:11
Where are we at with this?  Or should I just create a pull request and write this myself? Seems like it would be pretty straightforward to integrate lightsail here.

**Comment by dguido** [comment] 2017-04-13 21:14
That would be great! We're tied up with several other features right now.

**Comment by lordmuffin** [comment] 2017-04-14 02:03
Okay i have forked and hopefully i can get to this over the next couple weeks.

**Comment by RaminBourne** [comment] 2017-04-22 14:35
Hopefully almost here .. 👍

**Comment by davcarrington** [comment] 2017-07-04 06:18
Tried to install Algo on a Lightsail (Ubuntu) instance this evening. It failed. Will perhaps try again with a later release.

**Closed** 2017-07-16 22:58 UTC
Labels: cloud_provider_unsupported
