### ISSUE TITLE
Support for CentOS 7

### ISSUE THREAD

**Issue by JMoVS** [trailofbits/algo#732] opened 2017-11-20 07:50 UTC
### OS / Environment

CentOS 7

### Summary of the problem
It doesn't really work on CentOS 7

### Steps to reproduce the behavior
Trying to install it on CentOS 7

### The way of deployment (cloud or local)
cloud VPS

### Expected behavior
Did anybody figure out how to get it running on CentOS 7?

**Comment by gunph1ld** [comment] 2017-11-22 09:02
Duplicate of #227

**Closed by gunph1ld** 2017-11-22 09:02 UTC
