### ISSUE TITLE
Failing on GCE with  "the field 'args' has an invalid value, which appears to include a variable that is undefined. "

### ISSUE THREAD

**Issue by tuxcomputing** [trailofbits/algo#645] opened 2017-08-03 01:33 UTC
### OS / Environment
Windows10/Ubuntu

### Ansible version
ansible 2.2.0.0

### Version of components from `requirements.txt`
Name: msrestazure
Version: 0.4.11
Name: setuptools
Version: 36.2.7
Name: ansible
Version: 2.2.0.0
Name: dopy
Version: 0.3.5
Name: boto
Version: 2.48.0
Name: boto3
Version: 1.4.5
Name: azure
Version: 2.0.0rc5
Name: msrest
Version: 0.4.1
Name: apache-libcloud
Version: 2.1.0
Name: six
Version: 1.10.0
Name: pyOpenSSL
Version: 17.2.0
Name: Jinja2
Version: 2.8

### Summary of the problem
Installation fails on Google Cloud with error " "the field 'args' has an invalid value, which appears to include a variable that is undefined. "

### Steps to reproduce the behavior
Install Ubuntu on Windows 10, follow installation guide. Obtain GCE credentials .json and launch algo. Select the options from the below log. 

### The way of deployment (cloud or local)
cloud

### Expected behavior
-

### Actual behavior
-

### Full log

(env) root@DESKTOP-G1BF4RF:~/algo# ./algo

  What provider would you like to use?
    1. DigitalOcean
    2. Amazon EC2
    3. Microsoft Azure
    4. Google Compute Engine
    5. Install to existing Ubuntu 16.04 server

Enter the number of your desired provider
: 4

Enter the local path to your credentials JSON file (https://support.google.com/cloud/answer/6158849?hl=en&ref_topic=6262490#serviceaccounts):
: personal.json

Name the vpn server:
[algo]:

  What zone should the server be located in?
    1. Western US       (Oregon A)
    2. Western US       (Oregon B)
    3. Western US       (Oregon C)
    4. Central US       (Iowa A)
    5. Central US       (Iowa B)
    6. Central US       (Iowa C)
    7. Central US       (Iowa F)
    8. Eastern US       (Northern Virginia A)
    9. Eastern US       (Northern Virginia B)
    10. Eastern US      (Northern Virginia C)
    11. Eastern US      (South Carolina B)
    12. Eastern US      (South Carolina C)
    13. Eastern US      (South Carolina D)
    14. Western Europe  (Belgium B)
    15. Western Europe  (Belgium C)
    16. Western Europe  (Belgium D)
    17. Western Europe  (London A)
    18. Western Europe  (London B)
    19. Western Europe  (London C)
    20. Southeast Asia  (Singapore A)
    21. Southeast Asia  (Singapore B)
    22. East Asia       (Taiwan A)
    23. East Asia       (Taiwan B)
    24. East Asia       (Taiwan C)
    25. Northeast Asia  (Tokyo A)
    26. Northeast Asia  (Tokyo B)
    27. Northeast Asia  (Tokyo C)
    28. Australia       (Sydney A)
    29. Australia       (Sydney B)
    30. Australia       (Sydney C)
Please choose the number of your zone. Press enter for default (#14) zone.
[14]: 11

Do you want macOS/iOS clients to enable "VPN On Demand" when connected to cellular networks?
[y/N]: yy

Do you want macOS/iOS clients to enable "VPN On Demand" when connected to Wi-Fi?
[y/N]: y

List the names of trusted Wi-Fi networks (if any) that macOS/iOS clients exclude from using the VPN (e.g., your home network. Comma-separated value, e.g., HomeNet,OfficeWifi,AlgoWiFi)
:

Do you want to install a DNS resolver on this VPN server, to block ads while surfing?
[y/N]: y

Do you want each user to have their own account for SSH tunneling?
[y/N]: y

Do you want to apply operating system security enhancements on the server? (warning: replaces your sshd_config)
[y/N]: y

Do you want the VPN to support Windows 10 or Linux Desktop clients? (enables compatible ciphers and key exchange, less secure)
[y/N]: y

Do you want to retain the CA key? (required to add users in the future, but less secure)
[y/N]: y

PLAY [Configure the server] ****************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Generate the SSH private key] ********************************************
ok: [localhost]

TASK [Generate the SSH public key] *********************************************
ok: [localhost]

TASK [Change mode for the SSH private key] *************************************
ok: [localhost]

TASK [Ensure the dynamic inventory exists] *************************************
ok: [localhost]

TASK [cloud-gce : set_fact] ****************************************************
ok: [localhost]

TASK [cloud-gce : set_fact] ****************************************************
ok: [localhost]

TASK [cloud-gce : set_fact] ****************************************************
ok: [localhost]

TASK [cloud-gce : Network configured] ******************************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'unicode object' has no attribute 'client_email'\n\nThe error appears to have been in '/root/algo/roles/cloud-gce/tasks/main.yml': line 13, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: Network configured\n      ^ here\n"}

TASK [cloud-gce : debug] *******************************************************
ok: [localhost] => {
    "fail_hint": [
        "Sorry, but something went wrong!",
        "Please check the troubleshooting guide.",
        "https://trailofbits.github.io/algo/troubleshooting.html"
    ]
}

TASK [cloud-gce : fail] ********************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Failed as requested from task"}

PLAY RECAP *********************************************************************
localhost                  : ok=9    changed=0    unreachable=0    failed=1

**Comment by sosimon** [comment] 2017-08-03 14:28
Looks like the offending line/item is: https://github.com/trailofbits/algo/blob/master/roles/cloud-gce/tasks/main.yml#L21

`service_account_email` should already be defined on line 10, so I think line 21 should be `service_account_email: "{{ service_account_email }}"`

**Comment by tuxcomputing** [comment] 2017-08-09 17:57
tried to deploy from scaleway to google cloud and it worked without throwing that error. It still does not work on Windows :(

**Comment by martinAnsty** [comment] 2017-08-12 22:41
I had the same issue, checking the json credentials file downloaded from GCE showed there was indeed no client_email property

**Comment by gunph1ld** [comment] 2017-10-18 19:17
Can not reproduce. Following [the link provided ](https://support.google.com/cloud/answer/6158849?hl=en&ref_topic=6262490#serviceaccounts) I got the right credentials file with `client_email` included.

**Comment by gunph1ld** [comment] 2018-02-23 12:47
No info provided so far. Closing for now

**Closed by gunph1ld** 2018-02-23 12:47 UTC
Labels: needs_info

**Comment by lettucehead** [comment] 2018-03-16 21:48
I believe I have a related issue.
I am also on Win10 and GCE.
I do not receive an error message.
I _do_ have a `client_email` attribute.
However, I have waited several minutes with the `./algo` script being stopped at 
```TASK [cloud-gce : Network configured] **********************************************************************************```
When I pressed `Ctrl+C` it said:
`changed: [localhost]`
... and appears to be progressing.

**Comment by lettucehead** [comment] 2018-03-16 22:08
It "worked" in a way, but not 100%. I got the congrats message telling me to connect and check whoer.net to confirm.
However, following the instructions from README § "Configure the VPN Clients" or client-windows.md is impossible due to no windows_{user}.ps1 config. I can confirm this:
```(env) chaznix@DESKTOP:~/algo$ grep -r *.ps1 .
./env/lib/python2.7/site-packages/ansible/modules/system/setup.py:      exists on the target host. Files in this path MUST be PowerShell scripts (``*.ps1``) and
Binary file ./env/lib/python2.7/site-packages/ansible/modules/system/setup.pyc matches
./env/lib/python2.7/site-packages/pygments/lexers/_mapping.py:    'PowerShellLexer': ('pygments.lexers.shell', 'PowerShell', ('powershell', 'posh', 'ps1', 'psm1'), ('*.ps1', '*.psm1'), ('text/x-powershell',)),
Binary file ./env/lib/python2.7/site-packages/pygments/lexers/_mapping.pyc matches
./env/lib/python2.7/site-packages/pygments/lexers/shell.py:    filenames = ['*.ps1', '*.psm1']
Binary file ./env/lib/python2.7/site-packages/pygments/lexers/shell.pyc matches
(env) chaznix@DESKTOP:~/algo$ ssh -i configs/algo.pem ubuntu@35.193.4.123
Last login: Fri Mar 16 21:59:36 2018 from 24.130.187.224
ubuntu@algo:~$```
