### ISSUE TITLE
Azure deploy error - TASK [cloud-azure : Create an instance]

### ISSUE THREAD

**Issue by dialbat** [trailofbits/algo#891] opened 2018-04-25 02:18 UTC
### OS / Environment (where do you run Algo on)

```
Ubuntu on Win10
4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux
```

### Cloud Provider (where do you deploy Algo to)

```
AZURE
```

### Summary of the problem

All runs well, until it gets to TASK [cloud-azure : Create an instance].
Than i get this error
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error creating or updating virtual machine AlgoVPN - Azure Error: InvalidParameter\nMessage: The value of parameter linuxConfiguration.ssh.publicKeys.keyData is invalid.\nTarget: linuxConfiguration.ssh.publicKeys.keyData"}

### Steps to reproduce the behavior

1. Just follow the install steps and deployment

### Full log

```
What provider would you like to use?
    1. DigitalOcean
    2. Amazon Lightsail
    3. Amazon EC2
    4. Microsoft Azure
    5. Google Compute Engine
    6. Scaleway
    7. OpenStack (DreamCompute optimised)
    8. Install to existing Ubuntu 16.04 server (Advanced)

Enter the number of your desired provider
: 4

Enter your azure secret id (https://github.com/trailofbits/algo/blob/master/docs/cloud-azure.md)
You can skip this step if you want to use your defaults credentials from ~/.azure/credentials
[pasted values will not be displayed]
[...]:

Enter your azure tenant id (https://github.com/trailofbits/algo/blob/master/docs/cloud-azure.md)
You can skip this step if you want to use your defaults credentials from ~/.azure/credentials
[pasted values will not be displayed]
[...]:

Enter your azure client id (application id) (https://github.com/trailofbits/algo/blob/master/docs/cloud-azure.md)
You can skip this step if you want to use your defaults credentials from ~/.azure/credentials
[pasted values will not be displayed]
[...]:

Enter your azure subscription id (https://github.com/trailofbits/algo/blob/master/docs/cloud-azure.md)
You can skip this step if you want to use your defaults credentials from ~/.azure/credentials
[pasted values will not be displayed]
[...]:

Name the vpn server:
[algo]: AlgoVPN


  What region should the server be located in? (https://azure.microsoft.com/en-us/regions/)
    1.  South Central US
    2.  Central US
    3.  North Europe
    4.  West Europe
    5.  Southeast Asia
    6.  Japan West
    7.  Japan East
    8.  Australia Southeast
    9.  Australia East
    10. Canada Central
    11. West US 2
    12. West Central US
    13. UK South
    14. UK West
    15. West US
    16. Brazil South
    17. Canada East
    18. Central India
    19. East Asia
    20. Germany Central
    21. Germany Northeast
    22. Korea Central
    23. Korea South
    24. North Central US
    25. South India
    26. West India
    27. East US
    28. East US 2

Enter the number of your desired region:
[1]: 4

Do you want macOS/iOS clients to enable "VPN On Demand" when connected to cellular networks?
[y/N]: n

Do you want macOS/iOS clients to enable "VPN On Demand" when connected to Wi-Fi?
[y/N]: n

Do you want to install a DNS resolver on this VPN server, to block ads while surfing?
[y/N]: y

Do you want each user to have their own account for SSH tunneling?
[y/N]: y

Do you want the VPN to support Windows 10 or Linux Desktop clients? (enables compatible ciphers and key exchange, less secure)
[y/N]: y

Do you want to retain the CA key? (required to add users in the future, but less secure)
[y/N]: y

PLAY [Configure the server] ********************************************************************************************
TASK [Gathering Facts] *************************************************************************************************ok: [localhost]

TASK [Local pre-tasks] *************************************************************************************************included: /mnt/d/algo-master/playbooks/local.yml for localhost

TASK [Generate the SSH private key] ************************************************************************************ok: [localhost]

TASK [Generate the SSH public key] *************************************************************************************ok: [localhost]

TASK [Change mode for the SSH private key] *****************************************************************************ok: [localhost]

TASK [Ensure the dynamic inventory exists] *****************************************************************************ok: [localhost]

TASK [cloud-azure : set_fact] ******************************************************************************************ok: [localhost]

TASK [cloud-azure : Create a resource group] ***************************************************************************changed: [localhost]

TASK [cloud-azure : Create a virtual network] **************************************************************************changed: [localhost]

TASK [cloud-azure : Create a security group] ***************************************************************************changed: [localhost]

TASK [cloud-azure : Create a subnet] ***********************************************************************************changed: [localhost]

TASK [cloud-azure : Create an instance] ********************************************************************************fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error creating or updating virtual machine AlgoVPN - Azure Error: InvalidParameter\nMessage: The value of parameter linuxConfiguration.ssh.publicKeys.keyData is invalid.\nTarget: linuxConfiguration.ssh.publicKeys.keyData"}

TASK [cloud-azure : debug] *********************************************************************************************ok: [localhost] => {
    "fail_hint": [
        "Sorry, but something went wrong!",
        "Please check the troubleshooting guide.",
        "https://trailofbits.github.io/algo/troubleshooting.html"
    ]
}

TASK [cloud-azure : fail] **********************************************************************************************fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed as requested from task"}

PLAY RECAP *************************************************************************************************************localhost                  : ok=12   changed=4    unreachable=0    failed=2
```

**Comment by jackivanov** [comment] 2018-04-25 08:02
Known issue with WSL and ssh-keygen. Need to move to the native openssl modules, they should be available now

**Comment by jackivanov** [comment] 2018-04-25 09:36
@dialbat Just wait for the fix being released and we will close the issue.

**Comment by dialbat** [comment] 2018-04-25 09:39
thank you!

**Comment by dialbat** [comment] 2018-04-25 14:46
any idea when will update be released?

**Comment by jackivanov** [comment] 2018-04-26 10:43
Not a bug https://github.com/Microsoft/WSL/issues/81. Just place Algo outside of `/mnt` directory

**Comment by dialbat** [comment] 2018-05-11 18:43
My issues were resolved at second try. 
Seems like a timeout problem.

**Closed** 2018-09-02 18:54 UTC
Labels: documentation, needs_pr
