### ISSUE TITLE
New Wireguard configs required after ./algo update-users

### ISSUE THREAD

**Issue by TC1977** [trailofbits/algo#1131] opened 2018-09-27 18:51 UTC
**Describe the bug**
I don't have an Android phone, or a Wireguard client for that matter, and can't reproduce this.

Gitter.im report:

Krzysztof Szromek @szromek Sep 26 06:21
Hi guys! I've run into one issue - every time I update list of users, all Android clients stop working and they need to upload new Wireguard configs which is really hideous process. Is this something we can avoid?

**To Reproduce**

1. Install Algo with Wireguard clients on Android phones
2. Run ./algo update-users (I'd assume with `keys_clean_all` flag in `config.cfg` set to False)
3. Existing Wireguard clients won't work - have to download new config files

**Expected behavior**

Should be able to continue using existing Wireguard clients, without having to download new config files (unless of course the associated user was removed)

**Comment by jackivanov** [comment] 2018-10-04 11:28
I'm not able to reproduce. The old clients work well after updating users.

**Comment by conorsch** [comment] 2018-10-20 00:11
Definitely able to reproduce this one. It boils down to the user management logic supporting only a single operation: _append_ to list of users. If any other operation is performed, such as _removing_ a user, or even _reordering_ the list of users, clients connectivity can break. 

Intended to file an issue called "Algo user management doesn't support revocation", but chiming in on this discussion instead, since it appears to be the same underlying issue.

### Steps to reproduce
1. Clone clean algo config from master (I used efc8dc7620bc8692c8bd27f3b79fa8cd18d1bdaf)
2. Set up environment as described in docs
3. Run `./algo` and mostly stick to defaults, although make sure to store CA passphrase
4. Run `grep ^Address configs/<ALGO_IP>/wireguard/*.conf > round1` to store results for comparison
5. Edit `config.cfg` and move "dan" _after_ "jack"
6. Run `./algo update-users` and follow the prompts
7. Run `grep ^Address configs/<ALGO_IP>/wireguard/*.conf > round2` to store results for comparison
8. Run `diff round1 round2` to observe IP drift

As shown by step 8, the IPs assigned to users have changed, even though the _set_ of users is the same. This will lock out existing clients since their local configs no longer match what the server has.

### Thoughts on fixing
In order to support key revocation, the server would need to track state for previously issued users, keys, and IPs. When revoking, IPs can be "freed" up, but freeing up should _not_ cause configs for other, existing, still-valid users to be updated. 

Perhaps it would be sufficient to:

1. store the client info server-side in YAML (simply for ease of parsing)
2. read the the client info on every run of the user logic
3. _merge_ in "new" user logic to the existing client config

Some reconciliation may have to happen in 3), but nothing we couldn't handle with a small bit of Python. Thoughts on the explanation of outlined above, @TC1977 and @jackivanov? I'd be happy to take a crack at resolving as described, but there may be other aspects of the config subject to similar drift that I haven't noticed yet. Thoughts welcome.

**Comment by jackivanov** [comment] 2018-10-20 07:19
Yeah, thanks for the detailed clarification! Indeed, it may cause some issues in particular deployments, due to the config generation task which uses the sequential order of users to allocate ip addresses.
I've got an idea for that, will send a PR later

**Comment by jackivanov** [comment] 2018-10-20 08:41
@conorsch could you test it from the PR above, please?

**Comment by conorsch** [comment] 2018-10-21 19:52
@jackivanov Close, but I'm still able to cause collisions in the generated client configs. Using the same testing methodology above:

```
$ cat round1
configs/<ALGO_IP>/wireguard/dan.conf:Address = 10.19.49.101/32,fd9d:bc11:4021::101/48
configs/<ALGO_IP>/wireguard/jack.conf:Address = 10.19.49.102/32,fd9d:bc11:4021::102/48
$ cat round2
configs/<ALGO_IP>/wireguard/al.conf:Address = 10.19.49.101/32,fd9d:bc11:4021::101/48
configs/<ALGO_IP>/wireguard/dan.conf:Address = 10.19.49.101/32,fd9d:bc11:4021::101/48
configs/<ALGO_IP>/wireguard/jack.conf:Address = 10.19.49.102/32,fd9d:bc11:4021::102/48
```

While the `al` client got a new address, it reused an already provisioned address for the `dan` user. For completeness, here's the diff I applied to test the second "update-users" provisioning round:

```
diff --git a/config.cfg b/config.cfg
index f1721e5..f2f3eb5 100644
--- a/config.cfg
+++ b/config.cfg
@@ -3,6 +3,7 @@
 # Add as many users as you want for your VPN server here.
 # Credentials will be generated for each one.
 users:
+  - al
   - dan
   - jack
 ```
The behavior would still cause existing client certs to break.

**Comment by jackivanov** [comment] 2018-10-31 06:37
@conorsch thanks for the debug. The PR is above.

**Closed** 2018-11-12 17:03 UTC
Labels: bug
