### ISSUE TITLE
Error while adding a user.

### ISSUE THREAD

**Issue by Berokas** [trailofbits/algo#1601] opened 2019-10-06 13:09 UTC
Good day!

I am trying to add a user for the 1st time and I have noticed that when I start this I have to choose a server and I have onl one option localhost, actually this is not the real ip address that I am expecting. And in the end of the operation I get an error message, Here is the full error log:

(env) root@v220191010502398718:~/algo-master# ./algo update-users

PLAY [localhost] ***************************************************************

TASK [Get list of installed config files] **************************************
ok: [localhost]

TASK [Verify servers] **********************************************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [Build list of installed servers] *****************************************
ok: [localhost]
[Server address prompt]
Select the server to update user list below:
    1. localhost

:

TASK [Server address prompt] ***************************************************
ok: [localhost]

TASK [Set facts based on the input] ********************************************
ok: [localhost]

TASK [Import host specific variables] ******************************************
fatal: [localhost]: FAILED! => {"ansible_facts": {}, "ansible_included_var_files                                                                             ": [], "changed": false, "message": "Could not find or access 'configs/omit/.con                                                                             fig.yml'\nSearched in:\n\t/root/algo-master/vars/configs/omit/.config.yml\n\t/ro                                                                             ot/algo-master/configs/omit/.config.yml\n\t/root/algo-master/vars/configs/omit/.                                                                             config.yml\n\t/root/algo-master/configs/omit/.config.yml on the Ansible Controll                                                                             er.\nIf you are using a module and expect the file to exist on the remote, see t                                                                             he remote_src option"}
included: /root/algo-master/playbooks/rescue.yml for localhost

TASK [debug] *******************************************************************
ok: [localhost] => {
    "fail_hint": [
        "Sorry, but something went wrong!",
        "Please check the troubleshooting guide.",
        "https://trailofbits.github.io/algo/troubleshooting.html"
    ]
}

TASK [Fail the installation] ***************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed as requested fr                                                                             om task"}

PLAY RECAP *********************************************************************
localhost                  : ok=7    changed=0    unreachable=0    failed=1    s                                                                             kipped=0    rescued=1    ignored=0

(env) root@v220191010502398718:~/algo-master# ./algo update-users

PLAY [localhost] ***************************************************************

TASK [Get list of installed config files] **************************************
ok: [localhost]

TASK [Verify servers] **********************************************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [Build list of installed servers] *****************************************
ok: [localhost]
[Server address prompt]
Select the server to update user list below:
    1. localhost

:

TASK [Server address prompt] ***************************************************
ok: [localhost]

TASK [Set facts based on the input] ********************************************
ok: [localhost]

TASK [Import host specific variables] ******************************************
ok: [localhost]
[CA password prompt]
Enter the password for the private CA key (output is hidden):

TASK [CA password prompt] ******************************************************
ok: [localhost]

TASK [Set facts based on the input] ********************************************
ok: [localhost]

--> Please include the following block of text when reporting issues:

Algo running on: Ubuntu 18.04.3 LTS (Virtualized: kvm)
ZIP file created: 2019-10-05 19:31:30.000000000 +0200
.env/bin/python3 not found: has 'python3 -m virtualenv ...' been run?
Runtime variables:
    algo_provider "local"
    algo_ondemand_cellular "True"
    algo_ondemand_wifi "True"
    algo_ondemand_wifi_exclude "X251bGw="
    algo_dns_adblocking "True"
    algo_ssh_tunneling "True"
    wireguard_enabled "True"
    dns_encryption "True"

TASK [Display the invocation environment] **************************************
changed: [localhost -> localhost]

TASK [Install the requirements] ************************************************
ok: [localhost -> localhost]

TASK [Add the server to the vpn-host group] ************************************
changed: [localhost]

PLAY [User management] *********************************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [common : Check the system] ***********************************************
ok: [localhost]
included: /root/algo-master/roles/common/tasks/ubuntu.yml for localhost

TASK [common : Define facts] ***************************************************
ok: [localhost]

TASK [common : Set IPv6 support as a fact] *************************************
ok: [localhost]

TASK [common : Check size of MTU] **********************************************
ok: [localhost]
included: /root/algo-master/roles/wireguard/tasks/ubuntu.yml for localhost

TASK [wireguard : Set OS specific facts] ***************************************
ok: [localhost]

TASK [wireguard : Generate private keys] ***************************************
ok: [localhost] => (item=nabil)
ok: [localhost] => (item=razan)
ok: [localhost] => (item=kholoud)
ok: [localhost] => (item=daed)
ok: [localhost] => (item=ibrahim)
ok: [localhost] => (item=berna)
ok: [localhost] => (item=184.162.250.207)

TASK [wireguard : Generate preshared keys] *************************************
ok: [localhost] => (item=nabil)
ok: [localhost] => (item=razan)
ok: [localhost] => (item=kholoud)
ok: [localhost] => (item=daed)
ok: [localhost] => (item=ibrahim)
ok: [localhost] => (item=berna)
ok: [localhost] => (item=184.162.250.207)

TASK [wireguard : Generate public keys] ****************************************
ok: [localhost] => (item=nabil)
ok: [localhost] => (item=razan)
ok: [localhost] => (item=kholoud)
ok: [localhost] => (item=daed)
ok: [localhost] => (item=ibrahim)
ok: [localhost] => (item=berna)
ok: [localhost] => (item=184.162.250.207)

TASK [wireguard : Save public keys] ********************************************
ok: [localhost -> localhost] => (item=None)
ok: [localhost -> localhost] => (item=None)
ok: [localhost -> localhost] => (item=None)
ok: [localhost -> localhost] => (item=None)
ok: [localhost -> localhost] => (item=None)
ok: [localhost -> localhost] => (item=None)
ok: [localhost -> localhost] => (item=None)
ok: [localhost]

TASK [wireguard : WireGuard user list updated] *********************************
ok: [localhost -> localhost] => (item=nabil)
ok: [localhost -> localhost] => (item=razan)
ok: [localhost -> localhost] => (item=kholoud)
ok: [localhost -> localhost] => (item=daed)
ok: [localhost -> localhost] => (item=ibrahim)
ok: [localhost -> localhost] => (item=berna)

TASK [wireguard : set_fact] ****************************************************
ok: [localhost -> localhost]

TASK [wireguard : WireGuard users config generated] ****************************
ok: [localhost -> localhost] => (item=[0, u'nabil'])
ok: [localhost -> localhost] => (item=[1, u'razan'])
ok: [localhost -> localhost] => (item=[2, u'kholoud'])
ok: [localhost -> localhost] => (item=[3, u'daed'])
ok: [localhost -> localhost] => (item=[4, u'ibrahim'])
ok: [localhost -> localhost] => (item=[5, u'berna'])

TASK [wireguard : Generate QR codes] *******************************************
ok: [localhost -> localhost] => (item=[0, u'nabil'])
ok: [localhost -> localhost] => (item=[1, u'razan'])
ok: [localhost -> localhost] => (item=[2, u'kholoud'])
ok: [localhost -> localhost] => (item=[3, u'daed'])
ok: [localhost -> localhost] => (item=[4, u'ibrahim'])
ok: [localhost -> localhost] => (item=[5, u'berna'])

TASK [wireguard : WireGuard configured] ****************************************
ok: [localhost]
 [WARNING]: flush_handlers task does not support when conditional

TASK [strongswan : Set subjectAltName as a fact] *******************************
ok: [localhost -> localhost]

TASK [strongswan : debug] ******************************************************
ok: [localhost -> localhost] => {
    "subjectAltName": "IP:184.162.250.207,IP:2a03:4100:1a:7c7:28bd:69ff:fe06:a89                                                                             0"
}

TASK [strongswan : Ensure the pki directories exist] ***************************
ok: [localhost -> localhost] => (item=ecparams)
ok: [localhost -> localhost] => (item=certs)
ok: [localhost -> localhost] => (item=crl)
ok: [localhost -> localhost] => (item=newcerts)
ok: [localhost -> localhost] => (item=private)
ok: [localhost -> localhost] => (item=public)
ok: [localhost -> localhost] => (item=reqs)

TASK [strongswan : Ensure the config directories exist] ************************
ok: [localhost -> localhost] => (item=apple)
ok: [localhost -> localhost] => (item=manual)

TASK [strongswan : Ensure the files exist] *************************************
changed: [localhost -> localhost] => (item=.rnd)
changed: [localhost -> localhost] => (item=private/.rnd)
changed: [localhost -> localhost] => (item=index.txt)
changed: [localhost -> localhost] => (item=index.txt.attr)
changed: [localhost -> localhost] => (item=serial)

TASK [strongswan : Generate the openssl server configs] ************************
ok: [localhost -> localhost]

TASK [strongswan : Build the CA pair] ******************************************
ok: [localhost -> localhost]

TASK [strongswan : Copy the CA certificate] ************************************
ok: [localhost -> localhost]

TASK [strongswan : Generate the serial number] *********************************
ok: [localhost -> localhost]

TASK [strongswan : Build the server pair] **************************************
ok: [localhost -> localhost]

TASK [strongswan : Build the client's pair] ************************************
ok: [localhost -> localhost] => (item=nabil)
ok: [localhost -> localhost] => (item=razan)
ok: [localhost -> localhost] => (item=kholoud)
ok: [localhost -> localhost] => (item=daed)
ok: [localhost -> localhost] => (item=ibrahim)
failed: [localhost -> localhost] (item=berna) => {"ansible_loop_var": "item", "c                                                                             hanged": true, "cmd": "umask 077; openssl req -utf8 -new -newkey ec:ecparams/sec                                                                             p384r1.pem -config <(cat openssl.cnf <(printf \"[basic_exts]\\nsubjectAltName=DN                                                                             S:berna\")) -keyout private/berna.key -out reqs/berna.req -nodes -passin pass:\"                                                                             5GKjTWFu1LjLHK8N\" -subj \"/CN=berna\" -batch && openssl ca -utf8 -in reqs/berna                                                                             .req -out certs/berna.crt -config <(cat openssl.cnf <(printf \"[basic_exts]\\nsu                                                                             bjectAltName=DNS:berna\")) -days 3650 -batch -passin pass:\"5GKjTWFu1LjLHK8N\" -                                                                             subj \"/CN=berna\" && touch certs/berna_crt_generated\n", "delta": "0:00:00.0212                                                                             41", "end": "2019-10-06 14:55:23.006712", "item": "berna", "msg": "non-zero retu                                                                             rn code", "rc": 1, "start": "2019-10-06 14:55:22.985471", "stderr": "Generating                                                                              an EC private key\nwriting new private key to 'private/berna.key'\n-----\nUsing                                                                              configuration from /dev/fd/63\nunable to load CA private key\n139931927519680:er                                                                             ror:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:../crypto                                                                             /evp/evp_enc.c:537:\n139931927519680:error:23077074:PKCS12 routines:PKCS12_pbe_c                                                                             rypt:pkcs12 cipherfinal error:../crypto/pkcs12/p12_decr.c:63:\n139931927519680:e                                                                             rror:2306A075:PKCS12 routines:PKCS12_item_decrypt_d2i:pkcs12 pbe crypt error:../                                                                             crypto/pkcs12/p12_decr.c:94:\n139931927519680:error:0907B00D:PEM routines:PEM_re                                                                             ad_bio_PrivateKey:ASN1 lib:../crypto/pem/pem_pkey.c:88:", "stderr_lines": ["Gene                                                                             rating an EC private key", "writing new private key to 'private/berna.key'", "--                                                                             ---", "Using configuration from /dev/fd/63", "unable to load CA private key", "1                                                                             39931927519680:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad                                                                              decrypt:../crypto/evp/evp_enc.c:537:", "139931927519680:error:23077074:PKCS12 ro                                                                             utines:PKCS12_pbe_crypt:pkcs12 cipherfinal error:../crypto/pkcs12/p12_decr.c:63:                                                                             ", "139931927519680:error:2306A075:PKCS12 routines:PKCS12_item_decrypt_d2i:pkcs1                                                                             2 pbe crypt error:../crypto/pkcs12/p12_decr.c:94:", "139931927519680:error:0907B                                                                             00D:PEM routines:PEM_read_bio_PrivateKey:ASN1 lib:../crypto/pem/pem_pkey.c:88:"]                                                                             , "stdout": "", "stdout_lines": []}

PLAY RECAP *********************************************************************
localhost                  : ok=38   changed=3    unreachable=0    failed=1    s                                                                             kipped=12   rescued=0    ignored=0

(env) root@v220191010502398718:~/algo-master#

**Comment by jackivanov** [comment] 2019-10-06 13:13
> unable to load CA private key

The password you specified in `CA password prompt` is wrong

**Comment by Berokas** [comment] 2019-10-06 13:30
Thank you very much for the fast replay and I have a weird quesition! 
        "    \"#        The CA key password is 8GKjTWFu9ljLHK4N       #\"\n",

That was the password I got after finishing the setup and in that case my password is: 8GKjTWFu9ljLHK4N 
Do I need to type the spaces and symbols in the end as well? I have tried many times but it does not work. (I have changed the Password letters here)

Many thnx in advance,
Bero

**Comment by jackivanov** [comment] 2019-10-06 13:31
No spaces and no symbols just `8GKjTWFu9ljLHK4N`

**Comment by Berokas** [comment] 2019-10-06 13:35
@jackivanov 

I have tried to type the password in plain text and compared it to the original one and they are the same (so keyboard works and I am typing correctly)! But I am always getting the same error message after typing the password in putty ssh window. Could I maybe change the password?

Thnx

**Comment by darrylb-github** [comment] 2019-10-14 16:32
I'm seeing similar behaviour installing via the ansible scripts:

```
$ ansible-playbook users.yml -e "server=localhost ca_password=am1aWzgsuxAN@J3o"
...
ok: [localhost] => {
    "msg": [
        [
            "\"#                          Congratulations!                            #\"",
            "\"#                     Your Algo server is running.                     #\"",
            "\"#    Config files and certificates are in the ./configs/ directory.    #\"",
            "\"#              Go to https://whoer.net/ after connecting               #\"",
            "\"#        and ensure that all your traffic passes through the VPN.      #\"",
            "\"#                     Local DNS resolver 172.24.228.153                   #\"",
            ""
        ],
        "    \"#        The p12 and SSH keys password for new users is eRaWtUo_l       #\"\n",
        "    \"#        The CA key password is am1aWzgsuxAN@J3o       #\"\n",
        "    "
    ]
}
```

```
$ ansible-playbook users.yml -e "server=localhost ca_password=am1aWzgsuxAN@J3o"
...
TASK [strongswan : Revoke non-existing users] *****************************************************************************************************************************************************************
failed: [localhost -> localhost] (item=phone) => {"ansible_loop_var": "item", "changed": true, "cmd": "openssl ca -gencrl -config <(cat openssl.cnf <(printf \"[basic_exts]\\nsubjectAltName=DNS:phone\")) -passin pass:\"SqsL_xVa55kIuX2T\" -revoke certs/phone.crt -out crl/phone.crt\n", "delta": "0:00:00.009173", "end": "2019-10-14 16:28:42.615474", "item": "phone", "msg": "non-zero return code", "rc": 1, "start": "2019-10-14 16:28:42.606301", "stderr": "Using configuration from /dev/fd/63\nunable to load CA private key\n139755928228288:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:../crypto/evp/evp_enc.c:537:\n139755928228288:error:23077074:PKCS12 routines:PKCS12_pbe_crypt:pkcs12 cipherfinal error:../crypto/pkcs12/p12_decr.c:63:\n139755928228288:error:2306A075:PKCS12 routines:PKCS12_item_decrypt_d2i:pkcs12 pbe crypt error:../crypto/pkcs12/p12_decr.c:94:\n139755928228288:error:0907B00D:PEM routines:PEM_read_bio_PrivateKey:ASN1 lib:../crypto/pem/pem_pkey.c:88:", "stderr_lines": ["Using configuration from /dev/fd/63", "unable to load CA private key", "139755928228288:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:../crypto/evp/evp_enc.c:537:", "139755928228288:error:23077074:PKCS12 routines:PKCS12_pbe_crypt:pkcs12 cipherfinal error:../crypto/pkcs12/p12_decr.c:63:", "139755928228288:error:2306A075:PKCS12 routines:PKCS12_item_decrypt_d2i:pkcs12 pbe crypt error:../crypto/pkcs12/p12_decr.c:94:", "139755928228288:error:0907B00D:PEM routines:PEM_read_bio_PrivateKey:ASN1 lib:../crypto/pem/pem_pkey.c:88:"], "stdout": "", "stdout_lines": []}
```

**Comment by darrylb-github** [comment] 2019-10-15 09:07
Mine was an issue with not targeting the tag `-t update-users` :disappear:

i.e. `ansible-playbook users.yml -t update-users -e "server=localhost ca_password=am1aWzgsuxAN@J3o"` vs `ansible-playbook users.yml -e "server=localhost ca_password=am1aWzgsuxAN@J3o"`

**Comment by jackivanov** [comment] 2019-10-19 13:30
@Berokas if you still have this problem, try to run Algo from scratch and file a new issue then. I'm closing this for now as neither me nor TravisCI tests couldn't reproduce it.

**Closed by jackivanov** 2019-10-19 13:30 UTC

**Comment by rishabh1635** [comment] 2020-06-05 10:11
I'm also facing same issue, but here the problem is I forgot to saved the CA key password,
Is there any way to find out the CA key password.?

**Comment by luvpreetsingh** [comment] 2021-11-18 11:07
@rishabh1635 were you able to find out the CA password?
