### ISSUE TITLE
Unable to install ipsec mobileconfig file on mac

### ISSUE THREAD

**Issue by kdavidson007** [trailofbits/algo#14643] opened 2023-08-24 23:26 UTC
**Describe the bug**

When I try to install the the mobilconfig file in the the ipsec folder on a mac, I am now getting the following error: 

> Profile installation failed: The certificate could not be verified (authentication error).

**To Reproduce**

1. Double click the mobileconfig file here: configs -> ipsec -> apple -> desktop.mobileconfig 
2. From within the System Settings, click the Privacy and Security tab
3. Double click the profile 
4. Click install

**Additional context**

This type of file was working fine before the most recent update to algo.

**Comment by sameep** [comment] 2023-10-10 07:33
I'm getting the same error with mobileconfig. It seems to work fine when using the Wireguard config.

**Comment by zurk** [comment] 2023-12-22 10:13
> I'm getting the same error with mobileconfig. It seems to work fine when using the Wireguard config.

Same for me.

**Comment by sellersshrug0y** [comment] 2024-03-13 23:17
i’m also experiencing this issue

**Comment by kernelpanek** [comment] 2024-03-31 16:56
I'm also having issues with installing the mobileconfig files...

**Comment by manofaffairs** [comment] 2024-04-12 23:53
Experiencing the same issue here.

**Comment by stephenbrady** [comment] 2024-04-20 16:37
I reverted to fd6efb71f255739c1e50e8222c6c5fab99df5709, and the issue was cured for me. Looking at all the commits on master since, #14673 seems like the most likely culprit, but I have not actually isolated the regression to #14673.

**Comment by dguido** [comment] 2024-05-08 09:26
@jackivanov this looks like a real bug for MacOS 14 (Sonoma). #14558 looks related. Can you check these out? Thanks!
<img width="268" alt="Screenshot 2024-05-08 at 11 23 29 AM" src="https://github.com/trailofbits/algo/assets/294844/8219fe41-9599-417d-bcfd-52653222e113">

**Comment by jackivanov** [comment] 2024-05-09 03:10
#14718 should fix it

**Comment by jackivanov** [comment] 2024-05-10 02:05
https://github.com/trailofbits/algo/pull/14718 merged. I was able to install the profile on Somona with the fix

**Closed** 2024-05-10 02:05 UTC

**Comment by kernelpanek** [comment] 2024-05-12 21:44
Confirmed. Just built a new server and was able to install mobileprofile on MacOS Sonoma 14.4.1.
