### ISSUE TITLE
Could not deploy algo server - ./algo isn't running as it should

### ISSUE THREAD

**Issue by MayaBread** [trailofbits/algo#1837] opened 2020-07-07 08:25 UTC
Hello! I'm new to this algo server thing and I was interested. After doing all the steps with 0 issues, I wasn't able to run ./algo script at all. I've tried a lot of things and I've hit a roadblock. Can anyone help?

For context:
I'm running windows 10, ubuntu subsystem

**Full log**
(after running ./algo or bash algo)

[WARNING]: Could not match supplied host pattern, ignoring: vpn-host

PLAY [localhost] ****************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************************************************************************************************
fatal: [localhost]: UNREACHABLE! => {"changed": false, "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p \"` echo /home/maya/.ansible/tmp/ansible-tmp-1594109821.510544-179153507345316 `\" && echo ansible-tmp-1594109821.510544-179153507345316=\"` echo /home/maya/.ansible/tmp/ansible-tmp-1594109821.510544-179153507345316 `\" ), exited with result 1, stdout output: ansible-tmp-1594109821.510544-179153507345316=/home/maya/.ansible/tmp/ansible-tmp-1594109821.510544-179153507345316\n", "unreachable": true}

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0

**Comment by davidemyers** [comment] 2020-07-07 10:54
Looks like a duplicate of #1812.

**Comment by MayaBread** [comment] 2020-07-07 16:36
@davidemyers thank you! And apologies for over staying my welcome, but after finishing the setup there didn't seem to be any of the config files and certificates inside of "configs/". Is there any reason for this?

**Comment by davidemyers** [comment] 2020-07-07 17:01
So you switched to Ubuntu 18.04, ran `./algo` and chose to deploy to a cloud service, and got all the way to the "Congratulations!" message? Please post the output of:
```
ls -la configs
```

**Comment by MayaBread** [comment] 2020-07-07 17:30
I didn't switch to 18.04, in that thread there was a work around.. unless that's my problem.


Here's the output (the x's over the ip are deliberate)
I've ran through ./algo twice now which is why there are two ip directories.


(.env) maya@DESKTOP-6CC75O0:~/algo$ ls -la configs
total 4
drwxrwxr-x 1 maya maya  512 Jul  7 19:41 .
drwxrwxr-x 1 maya maya  512 Jul  7 19:37 ..
-rw-rw-r-- 1 maya maya    0 Jul  7 10:50 .gitinit
drwx------ 1 maya maya  512 Jul  7 19:48 34.105.xx.xx
drwx------ 1 maya maya  512 Jul  7 19:21 34.76.xx.xx
-rw------- 1 maya maya 1679 Jul  7 18:48 algo.pem
-rw-rw-rw- 1 maya maya  380 Jul  7 18:48 algo.pem.pub



(.env) maya@DESKTOP-6CC75O0:~/algo/configs/34.76.xx.xx$ ls
ipsec  ssh-tunnel  ssh_config  wireguard

**Comment by davidemyers** [comment] 2020-07-07 17:33
I'm not sure that workaround is adequate, but I don't have Windows so I can't confirm it.

That listing looks correct. Aren't there config files in the `ipsec` and `wireguard` directories?

**Comment by MayaBread** [comment] 2020-07-07 18:00
It is. Although, according to another guide (which referred me to this one) stated that there should be '<user>.p12' and 'windows_<user>.ps1' files inside the IP directory.

**Comment by davidemyers** [comment] 2020-07-07 18:06
Algo no longer supports using IPsec on Windows so that other guide is about a year out of date. Use WireGuard.

**Comment by MayaBread** [comment] 2020-07-07 18:07
How can I use it? Do I run it like a bash script or?

**Comment by davidemyers** [comment] 2020-07-07 18:08
See [here](https://github.com/trailofbits/algo#windows).

**Comment by MayaBread** [comment] 2020-07-07 18:10
Just to confirm. This is how I'm supposed to get the (user).p12/ps1 files? If so thank you!

**Comment by davidemyers** [comment] 2020-07-07 18:11
No, those files are no longer created. Use one of the `.conf` files in the `wireguard` directory.

**Closed** 2020-09-05 06:32 UTC
