### ISSUE TITLE
Install dnscrypt-proxy Failure

### ISSUE THREAD

**Issue by benmontour** [trailofbits/algo#1084] opened 2018-08-28 16:09 UTC
### OS / Environment (where do you run Algo on)

```
Ubuntu 18.04 LTS x64 deployed from MacOS 10.13.6
```

### Cloud Provider (where do you deploy Algo to)

```
DigitalOcean
```

### Summary of the problem

Running ./algo to initiate automated deploy to DigitalOcean

### Steps to reproduce the behavior

1. ./algo
2. Select DigitalOcean
3. Answer prompts
4. Input API Key
5. Wait for tasks
6. On TASK [dns_encryption : Install dnscrypt-proxy] the script fails

### Full log

```
fatal: [IPADDRESS]:
FAILED! => {"cache_update_time": 1535471922, "cache_updated": true, "changed": false, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"     
install 'dnscrypt-proxy'' failed: E: Sub-process /usr/bin/dpkg returned an error code (1)
", "rc": 100, "stderr": "E: Sub-process /usr/bin/dpkg returned an error code (1)
", "stderr_lines": ["E: Sub-process /usr/bin/dpkg returned an error code (1)"], "stdout": "Reading package lists...
Building dependency tree...
Reading state information...
The following package was automatically installed and is no longer required:
  grub-pc-bin
Use 'apt autoremove' to remove it.
The following NEW packages will be installed:
  dnscrypt-proxy
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 2140 kB of archives.
After this operation, 7990 kB of additional disk space will be used.
Get:1 http://ppa.launchpad.net/shevchuk/dnscrypt-proxy/ubuntu bionic/main amd64 dnscrypt-proxy amd64 2.0.16~ppa1~bionic [2140 kB]
Fetched 2140 kB in 5s (407 kB/s)
Selecting previously unselected package dnscrypt-proxy.
(Reading database ...
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 91587 files and directories currently installed.)
Preparing to unpack .../dnscrypt-proxy_2.0.16~ppa1~bionic_amd64.deb ...
Unpacking dnscrypt-proxy (2.0.16~ppa1~bionic) ...
Setting up dnscrypt-proxy (2.0.16~ppa1~bionic) ...
Job for dnsmasq.service failed because a fatal signal was delivered to the control process.
See \"systemctl status dnsmasq.service\" and \"journalctl -xe\" for details.
invoke-rc.d: initscript dnsmasq, action \"restart\" failed.
\u001b[0;1;31m*\u001b[0m dnsmasq.service - dnsmasq - A lightweight DHCP and caching DNS server
   Loaded: loaded (/lib/systemd/system/dnsmasq.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/dnsmasq.service.d
           `-100-CustomLimitations.conf
   Active: \u001b[0;1;31mfailed\u001b[0m (Result: signal) since Tue 2018-08-28 15:58:54 UTC; 18ms ago
  Process: 3952 ExecStop=/etc/init.d/dnsmasq systemd-stop-resolvconf (code=exited, status=0/SUCCESS)
  Process: 3959 ExecStartPre=/usr/sbin/dnsmasq --test \u001b[0;1;31m(code=killed, signal=KILL)\u001b[0m
 Main PID: 2947 (code=exited, status=0/SUCCESS)
      CPU: 229ms


Aug 28 15:58:50 algo systemd[1]: Stopped dnsmasq - A lightweight DHCP and caching DNS server.
Aug 28 15:58:50 algo systemd[1]: dnsmasq.service: Consumed 639ms CPU time
Aug 28 15:58:50 algo systemd[1]: Starting dnsmasq - A lightweight DHCP and caching DNS server...
Aug 28 15:58:54 algo systemd[1]: \u001b[0;1;39m\u001b[0;1;31m\u001b[0;1;39mdnsmasq.service: Control process exited, code=killed status=9\u001b[0m
Aug 28 15:58:54 algo systemd[1]: \u001b[0;1;39m\u001b[0;1;31m\u001b[0;1;39mdnsmasq.service: Failed with result 'signal'.\u001b[0m
Aug 28 15:58:54 algo systemd[1]: \u001b[0;1;31m\u001b[0;1;39m\u001b[0;1;31mFailed to start dnsmasq - A lightweight DHCP and caching DNS server.\u001b[0m
Aug 28 15:58:54 algo systemd[1]: dnsmasq.service: Consumed 229ms CPU time
dpkg: error processing package dnscrypt-proxy (--configure):
 installed dnscrypt-proxy package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 dnscrypt-proxy

", "stdout_lines": [
"Reading package lists...", 
"Building dependency tree...", 
"Reading state information...", 
"The following package was automatically installed and is no longer required:", 
"  grub-pc-bin", "Use 'apt autoremove' to remove it.", 
"The following NEW packages will be installed:", 
"  dnscrypt-proxy", "0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.", 
"Need to get 2140 kB of archives.", 
"After this operation, 7990 kB of additional disk space will be used.", 
"Get:1 http://ppa.launchpad.net/shevchuk/dnscrypt-proxy/ubuntu bionic/main amd64 dnscrypt-proxy amd64 2.0.16~ppa1~bionic [2140 kB]", 
"Fetched 2140 kB in 5s (407 kB/s)", 
"Selecting previously unselected package dnscrypt-proxy.", 
"(Reading database ... ", 
"(Reading database ... 5%", 
"(Reading database ... 10%", 
"(Reading database ... 15%", 
"(Reading database ... 20%", 
"(Reading database ... 25%", 
"(Reading database ... 30%", 
"(Reading database ... 35%", 
"(Reading database ... 40%", 
"(Reading database ... 45%", 
"(Reading database ... 50%", 
"(Reading database ... 55%", 
"(Reading database ... 60%", 
"(Reading database ... 65%", 
"(Reading database ... 70%", 
"(Reading database ... 75%", 
"(Reading database ... 80%", 
"(Reading database ... 85%", 
"(Reading database ... 90%", 
"(Reading database ... 95%", 
"(Reading database ... 100%", 
"(Reading database ... 91587 files and directories currently installed.)", 
"Preparing to unpack .../dnscrypt-proxy_2.0.16~ppa1~bionic_amd64.deb ...", 
"Unpacking dnscrypt-proxy (2.0.16~ppa1~bionic) ...", 
"Setting up dnscrypt-proxy (2.0.16~ppa1~bionic) ...", 
"Job for dnsmasq.service failed because a fatal signal was delivered to the control process.", 
"See \"systemctl status dnsmasq.service\" and \"journalctl -xe\" for details.", 
"invoke-rc.d: initscript dnsmasq, action \"restart\" failed.", 
"\u001b[0;1;31m*\u001b[0m dnsmasq.service - dnsmasq - A lightweight DHCP and caching DNS server", 
"   Loaded: loaded (/lib/systemd/system/dnsmasq.service; enabled; vendor preset: enabled)", 
"  Drop-In: /etc/systemd/system/dnsmasq.service.d", 
"           `-100-CustomLimitations.conf", 
"   Active: \u001b[0;1;31mfailed\u001b[0m (Result: signal) since Tue 2018-08-28 15:58:54 UTC; 18ms ago", 
"  Process: 3952 ExecStop=/etc/init.d/dnsmasq systemd-stop-resolvconf (code=exited, status=0/SUCCESS)", 
"  Process: 3959 ExecStartPre=/usr/sbin/dnsmasq --test \u001b[0;1;31m(code=killed, signal=KILL)\u001b[0m", 
" Main PID: 2947 (code=exited, status=0/SUCCESS)", 
"      CPU: 229ms", "", 
"Aug 28 15:58:50 algo systemd[1]: Stopped dnsmasq - A lightweight DHCP and caching DNS server.", 
"Aug 28 15:58:50 algo systemd[1]: dnsmasq.service: Consumed 639ms CPU time", 
"Aug 28 15:58:50 algo systemd[1]: Starting dnsmasq - A lightweight DHCP and caching DNS server...", 
"Aug 28 15:58:54 algo systemd[1]: \u001b[0;1;39m\u001b[0;1;31m\u001b[0;1;39mdnsmasq.service: Control process exited, code=killed status=9\u001b[0m", 
"Aug 28 15:58:54 algo systemd[1]: \u001b[0;1;39m\u001b[0;1;31m\u001b[0;1;39mdnsmasq.service: Failed with result 'signal'.\u001b[0m", 
"Aug 28 15:58:54 algo systemd[1]: \u001b[0;1;31m\u001b[0;1;39m\u001b[0;1;31mFailed to start dnsmasq - A lightweight DHCP and caching DNS server.\u001b[0m", 
"Aug 28 15:58:54 algo systemd[1]: dnsmasq.service: Consumed 229ms CPU time", "dpkg: error processing package dnscrypt-proxy (--configure):", " installed dnscrypt-proxy package post-installation script subprocess returned error exit status 1", 
"Errors were encountered while processing:", 
" dnscrypt-proxy"]}
```

**Comment by jackivanov** [comment] 2018-08-29 08:02
Can you make the full log more readable? Can't reproduce the issue and never had it before.

**Comment by benmontour** [comment] 2018-08-29 14:11
Just did fresh download and install. Fails in the exact same place. Something isn't right with the Install dnscrypt-proxy step.

**Comment by jackivanov** [comment] 2018-08-29 14:15
Everything seems OK, can't reproduce. I'm still waiting for the full log here.

**Comment by benmontour** [comment] 2018-08-29 14:17
What full log do you need? I have the error on "Install dnscrypt-proxy" included in original post. Happy to pull whatever logs you need.

**Comment by jackivanov** [comment] 2018-08-29 14:18
The whole log of the installation process

**Comment by benmontour** [comment] 2018-08-29 14:46
Is that the log you were looking for? If not, let me know where I can find it.

**Comment by benmontour** [comment] 2018-08-29 16:15
Ok, so on more digging, it's related to the dnsmasq memory limit you have set to 16384 kB. in 100-CustomLimitations.conf.j2.
I added a custom host file which I guess it to large to fit within this constraint. That's my bad for not mentioning that. As this appeared to be related to dnscrypt-proxy instead of dnsmasq.
Can this limit be increased or are there negative consequences to that?

**Comment by TC1977** [comment] 2018-08-29 16:17
I'd still suspect dnscrypt-proxy. If you run the Algo install without the custom host file, does it succeed? And then maybe you can plug in the host file later?

**Comment by benmontour** [comment] 2018-08-29 16:31
I can try that, what I did as a test was to double the MemoryLimit in /roles/dns_adblocking/templates/100-CustomLimitations.conf.j2 and everything installed just fine.

**Comment by jackivanov** [comment] 2018-08-30 12:35
> I added a custom host file which I guess it to large to fit within this constraint. That's my bad for not mentioning that

Any modifications on your own. 

I can't reproduce the issue on default settings, so, closing this for now

**Closed by jackivanov** 2018-08-30 12:35 UTC
